name: tilerush
description: "Block game built with Flutter and Flame."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  flame: ^1.33.0
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  patrol: ^4.1.0

patrol:
  app_name: "Tile Rush"
  android:
    package_name: com.example.tilerush

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
